### ISSUE TITLE
Limits of background update due to lack of context

### ISSUE THREAD

**Issue by Rarst** [markjaquith/WP-TLC-Transients#12]
In same fashion as wp-cron updates run without same context as place in code where they are triggered. This makes some things difficult:
- cannot use user-dependent data or code, since there is no user set up while update runs (example - things go haywire for me when using theme switcher plugin)
- cannot use query context of page (example - caching navigation menus with preserving `current` menu item is impossible)

I am not sure this is nicely solvable in context of the TLC Transients code (need time to think about it), but at least it needs to be explained in documentation as difference in mechanics to native transients.

**Comment by joehoyle** [comment]
Indeed, I don't think there is realistically any way to solve these issues 100%, but maybe should be outlined in the documentation perhaps. 

On a crazy tangent, would it in theory be possible on `shutdown` to call `fastcgi_finish_request` (only supported by PHP_FPM), then call the TLC callbacks? This was one could keep the scope of the Closures / callback functions and `$wp_query` etc.

**Comment by Rarst** [comment]
I remember there is also technique to disconnect user but keep script going (see http://stackoverflow.com/a/10464863/886380 ), not sure how robust it is.

**Comment by markjaquith** [comment]
@Rarst — couldn't you pass the necessary variables in as arguments to the callback? Like, pass in the current user ID, and have the callback do a user switch if that's not the current user?

**Comment by markjaquith** [comment]
Can also consider doing some limited automatic context preservation, but it might be confusing (and potentially harmful) if some context is preserved, but not all.

**Comment by tomjn** [comment]
+1 @markjaquith if your code requires ABC to grab the new content or whichever is needed, then relying on the context isn't reliable, nor should it be expected to be present for whatever reason. Passing in the needed information via a callback is the way to go.

E.g. If I'm using this to grab a URL specified in user meta, say an RSS feed from some service, I'd at least want to pass through the user ID and the service URL along and rely on the explicit data passed along, rather than the implicit data inferred from context.

**Comment by Rarst** [comment]
> couldn't you pass the necessary variables in as arguments to the callback? Like, pass in the current user ID, and have the callback do a user switch if that's not the current user?

Yes, definite possibility. Although what I am currently working on is caching intensive chunks of native WP functionality, which means callbacks/code I don't have direct control over.

Issues I see with trying to pass context:
- security - need to verify and prevent possibility of hijacking callback to run with context of different user
- timing - update runs on `init`, but some things (like my theme switcher) can be required to set up much earlier (no later than `setup_theme` in my case)

**Comment by markjaquith** [comment]
> security - need to verify and prevent possibility of hijacking callback to run with context of different user

So, neither the callback method nor its parameters are passed publicly in the spawning of the update server. They're stored with a key (hash of the transient key), and then the update server is called with that hash. The user doesn't get an opportunity to inject callback parameter values.

> timing

This one is harder. There are downsides to hooking early and there are downsides to hooking late. What if you could control when the update server spawned ran, per callback? Like, if you could provide a hook and a priority for it to attach to?

**Comment by Rarst** [comment]
> What if you could control when the update server spawned ran, per callback?

Interesting possibility. I am coming from current tangle of using theme switcher, but it's neither typical situation or completely representative of all-things-that-could-go-wrong without context.

Typical extension code has things that run immediately on load and things that run at appropriate hooks (`init` or earlier/later). Maybe there should be way to conveniently reproduce this workflow?

Have kind of "loader" for update that will run immediately and by default sets update up to fire on `init`, but can be overridden and/or adjusted.

**Comment by Rarst** [comment]
After coming back to this after a while I think pass necessary data with arguments and handle in callback is sufficient. So many things can be considered part of context it will just snowball into too big of a solution for something that can be done anyway.
