### ISSUE TITLE
updates_with() not working for callback method inside class

### ISSUE THREAD

**Issue by MickeyKay** [markjaquith/WP-TLC-Transients#32]
I'm trying to pass a class method to the `updates_with` method like so:

`$transient->updates_with( array( $this, 'fetch_api_data' ), $url );`

But it doesn't seem to be working. Is this not set up to work inside a class, or am I missing something perhaps?

**Comment by Rarst** [comment]
Note that updates are async (which is kind of the point). Your object will be serialized and stored, then unserialized to be run in separate environment. That very well might break it and require special wakeup handling.

**Comment by MickeyKay** [comment]
Thanks @Rarst . A few more questions to follow up. . .

How soon should the background callback fire? When I load the page the first time, it makes sense that nothing shows, right? However it seems like when I load it for the second time, a minute or so later, I my transient should've been set by then, right? By chance does this not work on localhost?

Secondly, what do you recommend for forcing the transient to run synchronously the first time (e.g. if it doesn't already exist)? Would something like this work:

```
if ( $transient->get() ) {
    $transient->background_only();
}

return $transient->get();
```

**Comment by Rarst** [comment]
Background only is opt-in, you should see result generated on first load by default.

**Comment by MickeyKay** [comment]
Right, but my question is, how would you running it in the background if and only if the transient is already set? That way it won't run the first time, but will run every time after that - so the only slow load will be the first one.

**Comment by Rarst** [comment]
I am not sure I follow.

Default behavior:
- first run, empty cache = sync generate
- following runs, filled cache = async generate on expire

`background_only()` behavior:
- first run, empty cache = trigger async generate, show nothing
- following runs, filled cache = async generate on expire

There is no reason to make `background_only()` conditional since just using it flips the first run logic one way or another.

**Comment by MickeyKay** [comment]
Got it. So the only difference is that background_only forces the async generate every time, including the first time?

**Comment by Rarst** [comment]
Yes, precisely. See [Examples](https://github.com/markjaquith/WP-TLC-Transients#examples) in readme. :)
